// <auto-generated />
using System;
using AcademicPlanner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AcademicPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(AcademicPlannerDbContext))]
    partial class AcademicPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcademicPlanner.Domain.Entities.Evaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Nota")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId")
                        .HasDatabaseName("IX_Evaluaciones_MateriaId");

                    b.HasIndex("MateriaId", "Fecha")
                        .HasDatabaseName("IX_Evaluaciones_MateriaId_Fecha");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("AcademicPlanner.Domain.Entities.HorarioCursada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aula")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("EsVirtual")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId")
                        .HasDatabaseName("IX_HorariosCursada_MateriaId");

                    b.ToTable("HorariosCursada", (string)null);
                });

            modelBuilder.Entity("AcademicPlanner.Domain.Entities.Materia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("NotaFinal")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Materias_Codigo");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("MateriasCorrelativas", b =>
                {
                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelativaRequeridaId")
                        .HasColumnType("uuid");

                    b.HasKey("MateriaId", "CorrelativaRequeridaId");

                    b.HasIndex("CorrelativaRequeridaId");

                    b.ToTable("MateriasCorrelativas", (string)null);
                });

            modelBuilder.Entity("AcademicPlanner.Domain.Entities.Evaluacion", b =>
                {
                    b.HasOne("AcademicPlanner.Domain.Entities.Materia", "Materia")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Evaluaciones_Materia");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("AcademicPlanner.Domain.Entities.HorarioCursada", b =>
                {
                    b.HasOne("AcademicPlanner.Domain.Entities.Materia", "Materia")
                        .WithMany("Horarios")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HorariosCursada_Materia");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("MateriasCorrelativas", b =>
                {
                    b.HasOne("AcademicPlanner.Domain.Entities.Materia", null)
                        .WithMany()
                        .HasForeignKey("CorrelativaRequeridaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MateriasCorrelativas_CorrelativaRequerida");

                    b.HasOne("AcademicPlanner.Domain.Entities.Materia", null)
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MateriasCorrelativas_Materia");
                });

            modelBuilder.Entity("AcademicPlanner.Domain.Entities.Materia", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
